### ISSUE TITLE
go dep doesn't support relative importing. 

### ISSUE THREAD

**Issue by manther** [datastream/holtwinters#1]
In your test file you have 
"../holtwinters"

https://github.com/golang/dep/issues/899

go dep doesn't support this type of importing. Is there anyway you could change so we can easily vender your lib?

I could open a PR as well. 

Thank you.

**Comment by klevron1** [comment]
Opened PR https://github.com/datastream/holtwinters/pull/2 to fix this.

**Comment by datastream** [comment]
Thank you. I have merged your patch.
